import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedInicioWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedBarraWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedPeliculasWidget2.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedPeliculasWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedPeliculasWidget3.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcartelerawidget/generated/GeneratedPeliculasWidget.dart';

/* Frame Cartelera
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarteleraWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 818.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.00640869140625,
                child: GeneratedInicioWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 116.0,
                child: GeneratedBarraWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 161.0,
                child: GeneratedPeliculasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 161.0,
                child: GeneratedPeliculasWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 161.0,
                child: GeneratedPeliculasWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 161.0,
                child: GeneratedPeliculasWidget3(),
              )
            ]),
      ),
    ));
  }
}
