import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedPeliculaWidget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedRectangle3Widget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedDuracionWidget9.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedLine3Widget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedDuracionWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedNombredelapeliculaWidget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedVermasWidget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpeliculaswidget4/generated/GeneratedRectangle4Widget4.dart';

/* Component Peliculas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPeliculasWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 161.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle3Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.34541062801932365;

                final double height =
                    constraints.maxHeight * 0.7701863354037267;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04106280193236715,
                      y: constraints.maxHeight * 0.08695652173913043,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle4Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.37922705314009664;

                final double height =
                    constraints.maxHeight * 0.17391304347826086;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4251207729468599,
                      y: constraints.maxHeight * 0.08695652173913043,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeliculaWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.37922705314009664;

                final double height =
                    constraints.maxHeight * 0.17391304347826086;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4251207729468599,
                      y: constraints.maxHeight * 0.40372670807453415,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedDuracionWidget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.37922705314009664;

                final double height =
                    constraints.maxHeight * 0.17391304347826086;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4251207729468599,
                      y: constraints.maxHeight * 0.546583850931677,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedDuracionWidget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.1570048309178744;

                final double height =
                    constraints.maxHeight * 0.15527950310559005;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.7922705314009661,
                      y: constraints.maxHeight * 0.7639751552795031,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedVermasWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5555555555555556;

                final double height =
                    constraints.maxHeight * 0.15527950310559005;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4251207729468599,
                      y: constraints.maxHeight * 0.2608695652173913,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedNombredelapeliculaWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.15217391304347827;
                double scaleX = (constraints.maxWidth * percentWidth) / 63.0;

                double percentHeight = 0.006211180124223602;
                double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7922705314009661,
                      translateY: constraints.maxHeight * 0.906832298136646,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedLine3Widget4())
                ]);
              }),
            )
          ]),
    ));
  }
}
