import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/Generated\$1500Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLunesymartesWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedAvLastorresWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedExitsharpWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedNOMBREWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedDIASDEDESCANSOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedSALARIOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedTaniaGarzaWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedBIENVENIDOEMPLEADODECINELITOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedSUCURSALWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedMatutinoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedHORARIOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedLine7Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 109.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 58.0,
                child: GeneratedBIENVENIDOEMPLEADODECINELITOWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 203.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 39.0,
                child: GeneratedTaniaGarzaWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 39.0,
                child: GeneratedAvLastorresWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 42.0,
                child: GeneratedMatutinoWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 39.0,
                child: GeneratedLunesymartesWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 42.0,
                child: Generated$1500Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 40.0,
                child: GeneratedNOMBREWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 35.0,
                child: GeneratedSUCURSALWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 35.0,
                child: GeneratedHORARIOWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 35.0,
                child: GeneratedSALARIOWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 33.0,
                child: GeneratedDIASDEDESCANSOWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 133.00375366210938,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 164.01219177246094,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 47.827178955078125,
                top: 427.5,
                right: null,
                bottom: null,
                width: 117.34564208984375,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 60.92738723754883,
                top: 558.5,
                right: null,
                bottom: null,
                width: 86.14522552490234,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 325.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 80.0,
                child: GeneratedExitsharpWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 236.0,
                child: GeneratedRectangle15Widget(),
              )
            ]),
      ),
    ));
  }
}
