import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedBarraWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedNumerodeentradasWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedSeleccionatushacientosWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedArrowdowncirclesharpWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedSELECCIONATUPELICULAAVERWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/Generated\$5065Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedPrecioWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedEscribetunumerodeentradasWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedInicioWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomprarticketwidget/generated/GeneratedLISTOWidget.dart';

/* Frame Comprar Ticket
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComprarTicketWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 818.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.00640869140625,
                child: GeneratedInicioWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 116.0,
                child: GeneratedBarraWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 79.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 47.0,
                child: GeneratedSELECCIONATUPELICULAAVERWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 35.0,
                child: GeneratedNumerodeentradasWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 35.0,
                child: GeneratedSeleccionatushacientosWidget(),
              ),
              Positioned(
                left: 206.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 38.0,
                child: GeneratedPrecioWidget(),
              ),
              Positioned(
                left: 309.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 50.0,
                child: GeneratedArrowdowncirclesharpWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 38.0,
                child: Generated$5065Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 34.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 28.0,
                child: GeneratedEscribetunumerodeentradasWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 217.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 39.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 695.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 27.0,
                child: GeneratedLISTOWidget(),
              )
            ]),
      ),
    ));
  }
}
