import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedINICIODESESIONWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediniciodesesionwidget/generated/GeneratedEmpleadoscinelitoWidget.dart';

/* Frame Inicio de sesion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIniciodesesionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 526.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 417.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 18.0,
                child: GeneratedINICIODESESIONWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 27.0,
                child: GeneratedEmpleadoscinelitoWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 74.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 74.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 74.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 832.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 33.0,
                child: GeneratedGroup6Widget(),
              )
            ]),
      ),
    ));
  }
}
